name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: node dist/index.mjs

  dedupe_check:
    name: Dedupe Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm dedupe --check --prefer-offline

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm format --list-different

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm lint

  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm lint:knip

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - uses: codecov/codecov-action@v5
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  type_check_current:
    name: Type Check (ESLint 10)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm typecheck

  type_check_legacy:
    name: Type Check (ESLint ${{ matrix.eslint-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        eslint-version:
          - 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm install -D eslint@${{ matrix.eslint-version }}
      - run: pnpm typecheck --project tsconfig.prod.json
