name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: node lib/index.mjs
  dedupe_check:
    name: Dedupe Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm dedupe --check --prefer-offline
  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm format --list-different
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm lint
  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm lint:knip
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - uses: codecov/codecov-action@v5
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  type_check:
    name: Type Check (ESLint ${{ matrix.eslint-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        eslint-version:
          - 9
          - 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm install -D eslint@${{ matrix.eslint-version }}
      - run: pnpm typecheck
